### PR TITLE
Doan Vinh Phu candidate

### PR DESCRIPTION
**Pull request by chuhaiphu**
The project deploy url: https://seahorse-app-z5vbq.ondigitalocean.app/track-one
I have implement:
Clean, readable, and maintainable code
Proper use of React hooks
Well-structured components
User-friendly UI/UX design

also, i use memo and useMemo hooks to have: 
Memoization for performance
Efficient handling of large lists

### CODE REVIEW

**Comment by minhtringuyennn** [comment]
Great work! You've completed the task in a very quick and efficient manner. Many props to you!

But there are few additional suggestions that might be helpful:

1. Currently, AFAIK the PR only implements the "Read" operation for products. However, the requirement is to handle the full CRUD operations (Create, Read, Update, Delete). It would be great of you to add those functionalities.

2. There are some redundant buttons in the UI that currently have no functionality. My suggestion is to either add personal information or meaningful content to these buttons, or remove any that lead to nowhere.

3. The product API is not fully functional at the moment because it’s referencing a local URL. If possible, it would be better to serve the frontend through the backend and ensure the API works properly on the deployed site. You can refer to the implementation in the image below for guidance.

CleanShot 2024-12-09 at 14 43 44@2x

4.  Additionally, you can consider using DigitalOcean Space to host your SQLite database externally, as explained in this [guide](https://litestream.io/guides/digitalocean/).

The first point is mandatory, while the other suggestions are optional and can be skipped. Keep up the great work, and happy coding!

**Comment by chuhaiphu** [comment]
I am adding full CRUD operation

**Comment by chuhaiphu** [comment]
I already implement full CRUDs operations, and also add react-hook-form for Form validation.
Also I implement a reusable modal dialog that can be customize and expandable with props.

**Comment by minhtringuyennn** [comment]
CleanShot 2024-12-09 at 21 09 53@2x
Great work so far! I noticed a couple of UI bugs, such as the input field being dark (I’m using dark mode) and some overlay issues, as shown in the attached image. You might also want to check out my comments on other PRs for ideas on improvements that can be applied here.

**Pull request closed without merging**
